//! Session identity and usage accumulation for one chat-completions request.
//!
//! [`ShimSessionId`] wraps the pin's [`CorrelationId`] so OTEL spans and
//! `aura.session_info` events carry the same identifier. [`UsageAccumulator`]
//! totals token usage across the coordinator loop's iterations and worker
//! loops, feeding the terminal `aura.usage` event.

use std::sync::Arc;

use agent_driver_rs::CorrelationId;
use agent_driver_rs::streaming::TokenUsage;

/// The session identity for one `/v1/chat/completions` request.
///
/// Wraps the pin's [`CorrelationId`] (itself a newtype over [`uuid::Uuid`]).
/// One session per request; OTEL spans and `aura.session_info` both carry it.
///
/// Forbidden invalid state: an empty or non-UUID session id. The private
/// inner field and the constructors ensure only a real `CorrelationId`
/// (generated by the pin's `Session` or by `CorrelationId::generate()`) can
/// produce a `ShimSessionId`.
///
/// Note (C8): id reuse across requests is a generation-time concern, not a
/// type-level one. `from_correlation` cannot prevent two requests from
/// sharing the same `CorrelationId` — that is the caller's responsibility.
/// In the shim, `build_request` generates a fresh id via
/// [`generate`](Self::generate) for each request; `from_correlation` is for
/// adopting an existing id from the pin's `Session`, not for per-request
/// generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ShimSessionId(CorrelationId);

impl ShimSessionId {
    /// Generate a fresh session id. Used when the shim needs an id before
    /// the `CoordinatorLoop`'s internal `Session` is constructed.
    #[must_use]
    pub fn generate() -> Self {
        Self(CorrelationId::generate())
    }

    /// Adopt an existing `CorrelationId`, typically from
    /// `Session::session_id()`.
    #[must_use]
    pub fn from_correlation(id: CorrelationId) -> Self {
        Self(id)
    }

    /// The underlying correlation id, for OTEL span attributes.
    pub fn correlation(&self) -> CorrelationId {
        self.0
    }

    /// The session id as a hyphenated UUID string, for `aura.session_info`
    /// and `aura.usage` payloads.
    pub fn as_str(&self) -> String {
        self.0.as_str()
    }
}

impl std::fmt::Display for ShimSessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Accumulates token usage across all iterations of a coordinator loop and
/// all worker loops inside it.
///
/// Fed by the [`UsageMeteringProvider`](super::usage_metering) decorator,
/// which intercepts every provider call's terminal `Completed` metadata.
/// The terminal `aura.usage` event reads the accumulated totals. A std
/// mutex (not tokio's) because the write site is the synchronous
/// `poll_next` of the metered stream, where sibling tool calls may poll
/// concurrently (the pin's driver runs same-response tools under
/// `join_all`); the critical section is a field update, never held
/// across an await.
///
/// Forbidden invalid state: negative token counts (`u64` prevents this);
/// double-counting from re-feeding the same iteration's usage (the
/// accumulator is append-only and does not deduplicate — see DESIGN.md
/// residual risk R2 for the worker-usage seam).
#[derive(Debug, Clone, Default)]
pub struct UsageAccumulator {
    prompt_tokens: u64,
    completion_tokens: u64,
}

impl UsageAccumulator {
    /// Create an empty accumulator.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Add one iteration's token usage.
    pub fn add(&mut self, usage: TokenUsage) {
        self.prompt_tokens += u64::from(usage.input_tokens);
        self.completion_tokens += u64::from(usage.output_tokens);
    }

    /// Total prompt (input) tokens across all iterations.
    #[must_use]
    pub fn prompt_tokens(&self) -> u64 {
        self.prompt_tokens
    }

    /// Total completion (output) tokens across all iterations.
    #[must_use]
    pub fn completion_tokens(&self) -> u64 {
        self.completion_tokens
    }

    /// Total tokens (prompt + completion).
    #[must_use]
    pub fn total_tokens(&self) -> u64 {
        self.prompt_tokens + self.completion_tokens
    }
}

/// A shareable handle to a [`UsageAccumulator`] behind a std mutex.
///
/// The metering decorator writes from the synchronous stream poll (where
/// sibling lanes may interleave); the observers read the totals at loop
/// completion. Both hold the guard only for field access, never across
/// an await.
#[must_use]
pub fn shared_accumulator() -> Arc<std::sync::Mutex<UsageAccumulator>> {
    Arc::new(std::sync::Mutex::new(UsageAccumulator::new()))
}
