//! Session identity and usage accumulation for one chat-completions request.
//!
//! [`ShimSessionId`] wraps the pin's [`CorrelationId`] so OTEL spans and
//! `aura.session_info` events carry the same identifier. [`UsageAccumulator`]
//! totals token usage across the coordinator loop's iterations and worker
//! loops, feeding the terminal `aura.usage` event.

use std::sync::Arc;

use agent_driver_rs::streaming::TokenUsage;
use agent_driver_rs::CorrelationId;
use tokio::sync::Mutex;

/// The session identity for one `/v1/chat/completions` request.
///
/// Wraps the pin's [`CorrelationId`] (itself a newtype over [`uuid::Uuid`]).
/// One session per request; OTEL spans and `aura.session_info` both carry it.
///
/// Forbidden invalid state: an empty or non-UUID session id; two requests
/// sharing one session id. The private inner field and the `from_correlation`
/// constructor ensure only a real `CorrelationId` (generated by the pin's
/// `Session` or by `CorrelationId::generate()`) can produce a `ShimSessionId`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ShimSessionId(CorrelationId);

impl ShimSessionId {
    /// Generate a fresh session id. Used when the shim needs an id before
    /// the `CoordinatorLoop`'s internal `Session` is constructed.
    #[must_use]
    pub fn generate() -> Self {
        Self(CorrelationId::generate())
    }

    /// Adopt an existing `CorrelationId`, typically from
    /// `Session::session_id()`.
    #[must_use]
    pub fn from_correlation(id: CorrelationId) -> Self {
        Self(id)
    }

    /// The underlying correlation id, for OTEL span attributes.
    pub fn correlation(&self) -> CorrelationId {
        self.0
    }

    /// The session id as a hyphenated UUID string, for `aura.session_info`
    /// and `aura.usage` payloads.
    pub fn as_str(&self) -> String {
        self.0.as_str()
    }
}

impl std::fmt::Display for ShimSessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Accumulates token usage across all iterations of a coordinator loop and
/// all worker loops inside it.
///
/// Fed from `AgentEvent::IterationComplete` (coordinator iterations) and from
/// worker-loop completion events (via the shared observer or `RunStore`).
/// The terminal `aura.usage` event reads the accumulated totals.
///
/// Forbidden invalid state: negative token counts (`u64` prevents this);
/// double-counting from re-feeding the same iteration's usage (the
/// accumulator is append-only and does not deduplicate — see DESIGN.md
/// residual risk R2 for the worker-usage seam).
#[derive(Debug, Clone, Default)]
pub struct UsageAccumulator {
    prompt_tokens: u64,
    completion_tokens: u64,
}

impl UsageAccumulator {
    /// Create an empty accumulator.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Add one iteration's token usage. Called from the shim observer's
    /// `IterationComplete` handler for the coordinator loop, and from
    /// whatever seam carries worker-loop usage (see DESIGN.md R2).
    pub fn add(&mut self, usage: TokenUsage) {
        self.prompt_tokens += u64::from(usage.input_tokens);
        self.completion_tokens += u64::from(usage.output_tokens);
    }

    /// Total prompt (input) tokens across all iterations.
    #[must_use]
    pub fn prompt_tokens(&self) -> u64 {
        self.prompt_tokens
    }

    /// Total completion (output) tokens across all iterations.
    #[must_use]
    pub fn completion_tokens(&self) -> u64 {
        self.completion_tokens
    }

    /// Total tokens (prompt + completion).
    #[must_use]
    pub fn total_tokens(&self) -> u64 {
        self.prompt_tokens + self.completion_tokens
    }
}

/// A shareable handle to a [`UsageAccumulator`] behind a tokio mutex.
///
/// The observer feeds usage from `on_event` (async), and the stream
/// completion path reads the totals to emit the final `aura.usage` event.
/// The `Arc<Mutex<UsageAccumulator>>` lets both sides access the same
/// accumulator without copying.
#[must_use]
pub fn shared_accumulator() -> Arc<Mutex<UsageAccumulator>> {
    Arc::new(Mutex::new(UsageAccumulator::new()))
}
